### ISSUE TITLE
Import ink format?

### ISSUE THREAD

**Issue by mahmoud** [inklewriter/freeinklewriter#30]
Thanks for the great software! Quick feature request for you (unless I'm missing something obvious):

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

Import seems to support only JSON format

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

I'd like to copy and paste (or upload / link to) a .ink file.

* **What is the motivation / use case for changing the behavior?**

Seems like plain-text authors use ink more often. I've got an ink file I'd like to walk through / visualize without using Unity or other heavyweight software.

* **Please tell us about your environment:**

https://www.inklewriter.com/

* **Other information** (e.g. detailed explanation, stacktraces, related issues

**Comment by maxence33** [comment]
Hi @mahmoud, 

Many thanks for your interest in this free version of inkle's inklewriter. 
If I understand well your request, you would like to be able to convert from Ink to Inklewriter so that you can read and edit your story in Inklewriter ?

At the moment we are basically using the converter created by Inkle that can be found here https://github.com/inkle/inklewriter-to-ink
As far as I know no converter has been created in order to convert the other way round, from Ink to Inklewriter. 

I am not even sure if this can be done. Probably an Ink editor offer functions that Inklewriter doesn't offer. So any conversion either way may not output "production grade" stories that can be used in Unity.

Maybe you can raise a ticket on the aforementionned Repo so that Inkle team can have a look into it. They will give you an indepth answer on the possibility to do this kind of conversion.

Provided this conversion can be done. I don't see a reason that would prevent us from generating Inklewriter stories based on an Ink source ( as long as the user know the limits of such process)

**Comment by albancrommer** [comment]
This has been confirmed as not possible.
