### ISSUE TITLE
Remove translation CLA

### ISSUE THREAD

**Issue by comradekingu** [inklewriter/freeinklewriter#54]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

~~https://hosted.weblate.org/projects/inklewriter/inklewriter-frontend/#information says CC-BY-**NC**.
This is not a libre license, and it is not compatible with AGPLv3+.~~

~~It can be changed to AGPLv3+ in
https://hosted.weblate.org/settings/inklewriter/inklewriter-frontend/~~

The CLA can be removed.
It is redundant to 6.4 in https://hosted.weblate.org/legal/terms/

If you add "kingu" I can possibly find other things to fix. :)

**Comment by albancrommer** [comment]
// Note for other team members : it is related to Weblate integration for translations //

Hi, @kingu, very impressed by your reactivity to open a contribution on weblate and thanks for your help.

I'm honestly a newbee on weblate so all the mess you've noticed is me messing around, trying to get the project to check all the marks in order to get it accepted for a free tier on hosted weblate. So please clarify a few things.
 
- CLA is the Contribution License Agreement? It seemed required by the weblate free software tier process.
- you want me to add you to the project on weblate? or in github?

Note: the git push configuration was broken on weblate, it is now repaired, you can submit some translations.

**Comment by comradekingu** [comment]
Since I am now added on Weblate I can see what the settings are.
A CLA is not required. It can be removed in https://hosted.weblate.org/settings/inklewriter/inklewriter-frontend/#basic
It does suggest populating the info field for instructions, but that is already done in https://hosted.weblate.org/settings/inklewriter/

Could add "GitHub pullrequest" as VCS in https://hosted.weblate.org/settings/inklewriter/inklewriter-frontend/#vcs though "Git" will work. https://docs.weblate.org/en/latest/vcs.html#github-pull-requestshttps://docs.weblate.org/en/latest/vcs.html#github-pull-requests

I don't understand why all the strings start with `fr.` Can I translate them like that?

**Comment by albancrommer** [comment]
Use your admin rights to their best! 

AFAI understand, the `fr.` prefix stems from the fact that the file I indicated as a base for translations was the french translations one, ie. `dictionary.fr.json`. That seems to work, since [your nb_NO  translation file](https://github.com/inklewriter/freeinklewriter/blob/dev/public/translations/dictionary.nb_NO.json) has the original EN strings as keys. 

Closing that Issue, feel free to contact me to discuss more.
